server:
  port: 8080


#application.yml
spring:
  datasource:   
        url: jdbc:mysql://127.0.0.1:3306/duanwu
        username: username
        password: ****
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

